const test = async (req, res, next) => {
    try {
        
        standartRespons.respons(res, result, 200, 'test')
    }
    catch (error) {

        const err = new createError.InternalServerError()
        next(err)
    }
}